/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-05-26 05:33:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Shoppers Heaven Homepage</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form name=\"homeForm\" method=\"post\">\r\n");
      out.write("\t\t<input name=\"homeInput\" type=\"hidden\">\r\n");
      out.write("\t\t<div></div>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<select name=\"searchCriteria\">\r\n");
      out.write("\t\t\t\t<option value=\"book\">Book</option>\r\n");
      out.write("\t\t\t\t<option value=\"fridge\">Fridge</option>\r\n");
      out.write("\t\t\t\t<option value=\"nailpolish\">Nail Polish</option>\r\n");
      out.write("\t\t\t\t<option value=\"tv\">T.V.</option>\r\n");
      out.write("\t\t\t</select> <input type=\"text\" name=\"seachName\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\tname=\"seachSubmit\" value=\"GO\" onclick=\"getSearchInput()\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p></p>\r\n");
      out.write("\t\t<p></p>\r\n");
      out.write("\t\t<div align=\"center\">Click on Image to See the Items</div>\r\n");
      out.write("\t\t<p></p>\r\n");
      out.write("\t\t<p></p>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<img src=\"../images/books.jpg\" width=\"300px 300px 300px 300px\"\r\n");
      out.write("\t\t\t\theight=\"300px 300px 300px 300px\" style=\"border: 0\"\r\n");
      out.write("\t\t\t\tonclick=\"getFormInput('books')\"> <img src=\"../images/tv.jpg\"\r\n");
      out.write("\t\t\t\twidth=\"300px 300px 300px 300px\" height=\"300px 300px 300px 300px\"\r\n");
      out.write("\t\t\t\tstyle=\"border: 0\" onclick=\"getFormInput('tvs')\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"../images/nailpolish.jpg\" width=\"300px 300px 300px 300px\"\r\n");
      out.write("\t\t\t\theight=\"300px 300px 300px 300px\" style=\"border: 0\"\r\n");
      out.write("\t\t\t\tonclick=\"getFormInput('nailpolishes')\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"../images/fridge.jpg\" width=\"300px 300px 300px 300px\"\r\n");
      out.write("\t\t\t\theight=\"300px 300px 300px 300px\" style=\"border: 0\"\r\n");
      out.write("\t\t\t\tonclick=\"getFormInput('fridges')\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction getFormInput(input) {\r\n");
      out.write("\t\tdocument.homeForm.homeInput.value = input;\r\n");
      out.write("\t\tdocument.homeForm.action = \"../HomeInputServlet\";\r\n");
      out.write("\t\tdocument.homeForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getSearchInput(){\r\n");
      out.write("\t\tdocument.homeForm.action = \"../HomeSearchServlet\";\r\n");
      out.write("\t\tdocument.homeForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
