/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-05-21 08:33:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.catalog.beans.BookBean;

public final class listBooks_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>List of Books</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t <div>\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;<a href=\"home.jsp\">Back</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table border=\"1\" align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>Book Cover</b> </td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>Product ID </b></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>Product Name</b></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>Company Name</b></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>Author Name</b></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>Genre</b></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>ISBN</b></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>Price</b></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>Description</b></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			if (session.getAttribute("bookBean") != null) {
				ArrayList<BookBean> arrayOfBbookBean = (ArrayList<BookBean>) session.getAttribute("bookBean");
				
				for(int i=0;i<arrayOfBbookBean.size();i++){
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><img src=\"");
      out.print(arrayOfBbookBean.get(i).getProductURL());
      out.write("\"\r\n");
      out.write("\t\t\t\twidth=\"300px 300px 300px 300px\" height=\"300px 300px 300px 300px\"\r\n");
      out.write("\t\t\t\tstyle=\"border: 0\" /></td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print(arrayOfBbookBean.get(i).getProdId());
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print(arrayOfBbookBean.get(i).getProductName());
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print(arrayOfBbookBean.get(i).getCompanyName());
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print(arrayOfBbookBean.get(i).getAuthorName());
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print(arrayOfBbookBean.get(i).getGenre());
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print(arrayOfBbookBean.get(i).getISBN());
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\"><b>$ ");
      out.print(arrayOfBbookBean.get(i).getPrice());
      out.write("</b></td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print(arrayOfBbookBean.get(i).getDescription());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			}
			
				}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div align=\"left\">\r\n");
      out.write("\t\t<a href=\"home.jsp\">Back</a>\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
